export const REGISTER_CLIENT_REQUEST = 'REGISTER_CLIENT_REQUEST';
export const REGISTER_CLIENT_SUCCESS = 'REGISTER_CLIENT_SUCCESS';
export const REGISTER_CLIENT_FAILURE = 'REGISTER_CLIENT_FAILURE';
export const REGISTER_CLIENT_LOAD_FROM_LOCAL = 'REGISTER_CLIENT_LOAD_FROM_LOCAL';
export const CHECK_PERMISSION_SUCCESS = 'CHECK_PERMISSION_SUCCESS';


export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN_RELOGIN = 'LOGIN_RELOGIN';


export const FETCH_API_REQUEST = 'FETCH_API_REQUEST';
export const FETCH_API_SUCCESS = 'FETCH_API_SUCCESS';
export const FETCH_API_FAILURE = 'FETCH_API_FAILURE';

export const GET_CACHE_REQUEST = 'GET_CACHE_REQUEST';
export const GET_CACHE_SUCCESS = 'GET_CACHE_SUCCESS';
export const GET_CACHE_FAILURE = 'GET_CACHE_FAILURE';
export const GET_CACHE_FROM_LOCAL = 'GET_CACHE_FROM_LOCAL';

export const LOGOUT = 'LOGOUT';
export const PAGE_UPDATEPATH = "PAGE_UPDATEPATH";

export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';

export const MODAL_TYPE_NOTIFICATION = 'MODAL_TYPE_NOTIFICATION';
export const MODAL_TYPE_CONFIRMATION = 'MODAL_TYPE_CONFIRMATION';
export const MODAL_TYPE_PREVIEWMEDIA = 'MODAL_TYPE_PREVIEWMEDIA';
export const MODAL_TYPE_COMMONTMODALS = 'MODAL_TYPE_COMMONTMODALS';
export const MODAL_TYPE_SEARCH = 'MODAL_TYPE_SEARCH';
export const MODAL_TYPE_CONFIRMATIONNEW = 'MODAL_TYPE_CONFIRMATIONNEW';
export const MODAL_TYPE_CONFICOMPONET = 'MODAL_TYPE_CONFICOMPONET';
export const MODAL_TYPE_IMAGE_SLIDE = 'MODAL_TYPE_IMAGE_SLIDE';
export const MODAL_TYPE_VIEW = 'MODAL_TYPE_VIEW';
export const MODAL_TYPE_DOWNLOAD_EXCEL = 'MODAL_TYPE_DOWNLOAD_EXCEL';
export const MODAL_TYPE_SHOWDOWNLOAD_EXCEL = 'MODAL_TYPE_SHOWDOWNLOAD_EXCEL';

